version: "3.8"

services:
  backend:
    build: "."
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./client/src:/app/src
    depends_on:
      - backend
